# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/program/vivado_workspace/vga_exp/vga_exp.cache/wt [current_project]
set_property parent.project_path E:/program/vivado_workspace/vga_exp/vga_exp.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/program/vivado_workspace/vga_exp/vga_exp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/program/vivado_workspace/vga_exp/coe/test7.coe
add_files E:/program/vivado_workspace/vga_exp/coe/smile.coe
add_files E:/program/vivado_workspace/vga_exp/coe/die.coe
add_files E:/program/vivado_workspace/vga_exp/coe/win.coe
read_verilog -library xil_defaultlib {
  E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/imports/source/debounce.v
  E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/imports/source/vga_timing.v
  E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/imports/source/top_flyinglogo.v
}
read_ip -quiet E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
set_property used_in_implementation false [get_files -all e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc]
set_property used_in_implementation false [get_files -all e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc]
set_property used_in_implementation false [get_files -all e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc]
set_property is_locked true [get_files E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/dcm_25m/dcm_25m.xci]

read_ip -quiet E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/smile_rom/smile_rom.xci
set_property used_in_implementation false [get_files -all e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/smile_rom/smile_rom_ooc.xdc]
set_property is_locked true [get_files E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/smile_rom/smile_rom.xci]

read_ip -quiet E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/die_rom/die_rom.xci
set_property used_in_implementation false [get_files -all e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/die_rom/die_rom_ooc.xdc]
set_property is_locked true [get_files E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/die_rom/die_rom.xci]

read_ip -quiet E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/win_rom/win_rom.xci
set_property used_in_implementation false [get_files -all e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/win_rom/win_rom_ooc.xdc]
set_property is_locked true [get_files E:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/win_rom/win_rom.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/program/vivado_workspace/vga_exp/vga_exp.srcs/constrs_1/new/vga_exp.xdc
set_property used_in_implementation false [get_files E:/program/vivado_workspace/vga_exp/vga_exp.srcs/constrs_1/new/vga_exp.xdc]


synth_design -top top_flyinglogo -part xc7a35tcsg324-1


write_checkpoint -force -noxdef top_flyinglogo.dcp

catch { report_utilization -file top_flyinglogo_utilization_synth.rpt -pb top_flyinglogo_utilization_synth.pb }
