# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/logo_rom/logo_rom.xci
# IP: The module: 'logo_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/logo_rom/logo_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logo_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/logo_rom/logo_rom.xci
# IP: The module: 'logo_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/program/vivado_workspace/vga_exp/vga_exp.srcs/sources_1/ip/logo_rom/logo_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logo_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
